services:
  backend:
    build:
      context: backend
      target: builder
    container_name: api
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    networks:
      - public
      - private
    restart: "no"
    depends_on:
      - db
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  adminer:
    image: adminer
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      - public
      - private
    ports:
      - 8080:8080
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend:/project
      - /project/node_modules
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: db/password.txt